
application-version: @project.version@
application-name: @project.name@


spring:
  jpa:
    show-sql : false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
     org:
      springframework:
           security: DEBUG
