


spring:
  jpa:
    show-sql : false
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true # disable swagger default pet store api
logging:
  level:
     org:
      springframework:
           security: DEBUG
