INSERT INTO COUNTRY values(1,'Maroc');


INSERT INTO CATEGORY values (1, 'All categories', 'assets/CategorieImage/tout.png','All');
INSERT INTO CATEGORY values(2, 'Burgers', 'assets/CategorieImage/Burgers.jpg','Burger');
INSERT INTO CATEGORY values(3,'italien foods','assets/CategorieImage/italien.jpg', 'italien');
INSERT INTO CATEGORY values(4,'Asian foods','assets/CategorieImage/asiatique.jpg', 'Asiatique');
INSERT INTO CATEGORY values(5, 'Le marché', 'assets/CategorieImage/marché.jpg','Marché');
INSERT INTO CATEGORY values(6,'Epicerie','assets/CategorieImage/epicerie.jpg' ,'Epicerie');

INSERT INTO CITY values(1,'Afourar', 1);
INSERT INTO CITY values(2,'Agadir', 1);
INSERT INTO CITY values(3,'Al Hoceïma', 1);
INSERT INTO CITY values(4,'Assilah', 1);
INSERT INTO CITY values(5,'Azemmour', 1);
INSERT INTO CITY values(6,'Azilal', 1);
INSERT INTO CITY values(7,'Azrou', 1);
INSERT INTO CITY values(8,'Ben Guerir', 1);
INSERT INTO CITY values(9,'Beni Mellal', 1);
INSERT INTO CITY values(10,'Berkane', 1);
INSERT INTO CITY values(11,'Berrechid', 1);
INSERT INTO CITY values(12,'Boujdour', 1);
INSERT INTO CITY values(13,'Bouskoura', 1);
INSERT INTO CITY values(14,'Casablanca', 1);
INSERT INTO CITY values(15,'Chefchaouen', 1);
INSERT INTO CITY values(16,'Dakhla', 1);
INSERT INTO CITY values(17,'Essaouira', 1);
INSERT INTO CITY values(18,'El Jadida', 1);
INSERT INTO CITY values(19,'Errachidia', 1);
INSERT INTO CITY values(20,'Fès', 1);
INSERT INTO CITY values(21,'Guelmim', 1);
INSERT INTO CITY values(22,'Ifrane', 1);
INSERT INTO CITY values(23,'Inezgane', 1);
INSERT INTO CITY values(24,'Khouribga', 1);
INSERT INTO CITY values(25,'Laayoune', 1);
INSERT INTO CITY values(26,'Larache', 1);
INSERT INTO CITY values(27,'Marrakech', 1);
INSERT INTO CITY values(28,'Meknès', 1);
INSERT INTO CITY values(29,'Mohammédia', 1);
INSERT INTO CITY values(30,'Nador', 1);
INSERT INTO CITY values(31,'Ouarzazate', 1);
INSERT INTO CITY values(32,'Oujda', 1);
INSERT INTO CITY values(33,'Rabat', 1);
INSERT INTO CITY values(34,'Safi', 1);
INSERT INTO CITY values(35,'Salé', 1);
INSERT INTO CITY values(36,'Settat', 1);
INSERT INTO CITY values(37,'Tanger', 1);
INSERT INTO CITY values(38,'Taza', 1);
INSERT INTO CITY values(39,'Tétouan', 1);
INSERT INTO CITY values(40,'Tiznit ', 1);
INSERT INTO CITY values(41,'Youssoufia', 1);
INSERT INTO CITY values(42,'Zagora', 1);